name: tests
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - "*"

permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,bioconda,defaults
          channel-priority: strict

      - name: Install conda dependencies
        run: |
          conda install pip pytest coverage

      - name: Install pip dependencies
        run: | 
          pip install hatch

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm graphviz

      - name: Run tests
        shell: bash
        run: |
          conda activate test-env
          hatch run snakemake:cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
