name: tests

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - "*"

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10.x, 3.11, 3.12]
        snakemake-version: [7.32.4, ">8"]
        exclude:
          # Exclude incompatible combinations
          - python-version: 3.9
            snakemake-version: ">8"
          - python-version: 3.10
            snakemake-version: ">8"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          channels: conda-forge,bioconda,defaults
          channel-priority: strict

      - name: Install pip dependencies
        run: |
          pip install hatch

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm clang build-essential graphviz

      - name: Set up Hatch environment
        run: |
          hatch env create snakemake -M python=${{ matrix.python-version }} snakemake=${{ matrix.snakemake-version }}
          hatch env select snakemake

      - name: Run tests
        shell: bash
        env:
          AR: /usr/bin/ar
        run: |
          hatch run snakemake:cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: ${{ matrix.python-version }}-snakemake-${{ matrix.snakemake-version }}
