name: tests

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - "*"

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", 3.11, 3.12]
        snakemake-version: ["==7.32.4", ">8"]
        exclude:
          # Exclude incompatible combinations
          - python-version: 3.8
            snakemake-version: ">8"
          - python-version: 3.9
            snakemake-version: ">8"
          - python-version: "3.10"
            snakemake-version: ">8"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          channels: conda-forge,bioconda,defaults
          channel-priority: strict

      - name: Install pip dependencies
        run: |
          pip install hatch

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm clang build-essential graphviz

      - name: Run tests
        env:
          AR: /usr/bin/ar
        shell: bash
        run: |
          hatch python install ${{ matrix.python-version }}
          hatch --env "snakemake.py${{ matrix.python-version }}-${{ matrix.snakemake-version }}" run cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: ${{ matrix.python-version }}-snakemake-${{ matrix.snakemake-version }}
